---
- name: Install sway and utilities
  become: True
  apt:
    package:
      - sway
      - grim
      - slurp
      - wl-clipboard

- name: Install custom packages
  become: True
  apt:
    package: "{{ sway_custom_packages }}"

- name: Ensure configuration directory exists
  file:
    path: ~/.config/sway/config.d
    state: directory

- name: Configure sway
  template:
    src: sway-config.j2
    dest: ~/.config/sway/config
  when: sway_full_config | length == 0

- name: Configure keybindings, autostarts, etc.
  template:
    src: "{{ item }}.j2"
    dest: "~/.config/sway/config.d/{{ item }}"
  with_items:
    - 00-extra-early
    - 20-autostart
    - 50-keybindings
    - 99-extra-late
  when: sway_full_config | length == 0

- name: Configure sway (standalone)
  template:
    src: sway-config-full.j2
    dest: ~/.config/sway/config
  when: sway_full_config | length > 0
